title:   Assel Irmaganbetova
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 My name is Assel, a Data Analyst / Business Intelligence Engineer stuffed with 7-years O&G experience. I am passionate about exploring and analyzing data. 
  <br><br>
  <a href="https://www.linkedin.com/in/airmaganbetova/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/assel8809">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/asselirmaganbetova/Portfolio-Assel-Irmaganbetova-ec18a696499f4f9cbcf2736bf8bd3776">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal 
 
